AllCops:
  NewCops: disable

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Semicolon:
  Enabled: false
